# -*- coding: utf-8 -*-
"""Manipulasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-fH9WrQy9DKz0kC8j6LsO5vGj5IP6YG

string
"""

nama = "rosyan"
asal = "indonesia"

print(nama)

"""manipulasi string"""

print(nama, asal)

print("halo nama saya", nama)

print("halo nama saya", nama, "asal saya dari", asal)

data_lengkap = nama + asal
print(data_lengkap)

"""string + non string"""

asal_kota = "kuningan"
kode_pos = 45556

asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota *3
print(asal_kota_x3)